In [3]:
import cv2

In [4]:
# !pip install opencv-python

In [5]:
cv2.__version__

'4.5.5'

In [12]:
img = cv2.imread("lenna.bmp")

In [13]:
img.shape  #(가로세로 길이와 3컬러)

(512, 512, 3)

In [14]:
img   # 125, 137, 226   B G R

array([[[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       [[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       [[125, 137, 226],
        [125, 137, 226],
        [133, 137, 223],
        ...,
        [122, 148, 230],
        [110, 130, 221],
        [ 90,  99, 200]],

       ...,

       [[ 60,  18,  84],
        [ 60,  18,  84],
        [ 58,  27,  92],
        ...,
        [ 84,  73, 173],
        [ 76,  68, 172],
        [ 79,  62, 177]],

       [[ 57,  22,  82],
        [ 57,  22,  82],
        [ 62,  32,  96],
        ...,
        [ 79,  70, 179],
        [ 81,  71, 181],
        [ 81,  74, 185]],

       [[ 57,  22,  82],
        [ 57,  22,  82],
        [ 62,  32,  96],
        ...,
        [ 79,  70, 179],
        [ 81,  71, 181],
        [ 81,  74, 185]]

In [ ]:
if img.any():
    cv2.namedWindow('Image')
    cv2.imshow('image', img)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [15]:
img1 = cv2.imread('cat.bmp', cv2.IMREAD_GRAYSCALE)

In [16]:
img1.shape

(480, 640)

In [17]:
import numpy as np

In [18]:
np.zeros((2, 3), np.uint8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [19]:
np.ones((2,3), np.uint8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [20]:
np.full((2,3), 1.2, np.float32)

array([[1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2]], dtype=float32)

In [21]:
np.empty((2, 3), np.uint8)    # 자리는 어떻고

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [24]:
mat1 = np.array([[11, 12, 13, 14],
                    [21, 22, 23, 24],
                    [31, 32, 33, 34]]).astype(np.uint8)

In [26]:
type(mat1)

numpy.ndarray

In [ ]:
# numpy 활용

In [29]:
mat1 = mat1.astype(np.uint8)

In [30]:
mat1.dtype

dtype('uint8')

In [31]:
mat1[0,1] = 100
mat1

array([[ 11, 100,  13,  14],
       [ 21,  22,  23,  24],
       [ 31,  32,  33,  34]], dtype=uint8)

In [32]:
mat1[2, :] = 200
mat1

array([[ 11, 100,  13,  14],
       [ 21,  22,  23,  24],
       [200, 200, 200, 200]], dtype=uint8)

In [35]:
mat1[2, 1:3] = 30
mat1

array([[ 11, 100,  13,  14],
       [ 21,  22,  23,  24],
       [200,  30,  30, 200]], dtype=uint8)

In [37]:

img1 = cv2.imread('cat.bmp')

img2 = img1
img3 = img1.copy()

img1[:, :] = (0, 255, 255)  # yellow

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey()
cv2.destroyAllWindows()


In [39]:
img1 = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)

img2 = img1[200:400, 200:400]
img3 = img1[200:400, 200:400].copy()

img2 += 20        # 밝기 증가

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('img3', img3)
cv2.waitKey()
cv2.destroyAllWindows()

In [40]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.arange(12).reshape(3, 4).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
mat1 = np.ones((3, 4), np.int32)    # 1's matrix
mat1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:

mat2 = np.arange(12).reshape(3, 4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
mat3 = mat1 + mat2
mat3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
mat4 = mat2 * 2
mat4

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [48]:
#4장 video.py

In [3]:
cap = cv2.VideoCapture('stopwatch.avi')

In [4]:
cap.get(cv2.CAP_PROP_FRAME_WIDTH)

640.0

In [5]:
cap.get(cv2.CAP_PROP_FRAME_HEIGHT)

480.0

In [6]:
cap.get(cv2.CAP_PROP_FRAME_COUNT)

378.0

In [7]:
fps= cap.get(cv2.CAP_PROP_FPS)   # 초당 30장을 보여준다.
fps

30.0

In [8]:
378/30    #동영상의 길이 12초

12.6

In [9]:
delay = round(1000/fps)
delay

33

In [10]:
ret, frame = cap.read()

In [11]:
ret   # True = 그림이 있다.   재생이 끝나면 False

True

In [12]:
frame.shape

(480, 640, 3)

In [13]:
frame[0][0]

array([29, 30, 60], dtype=uint8)

In [14]:
inversed = ~frame

In [15]:
inversed[0][0]

array([226, 225, 195], dtype=uint8)

In [16]:
frame[0][0] + inversed[0][0]

array([255, 255, 255], dtype=uint8)

In [18]:
inversed = ~frame

In [ ]:
while True:
    ret, frame = cap.read()
    if not ret:
        break
    inversed = ~frame
    cv2.imshow('frame', frame)
    cv2.imshow('inversed', inversed)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2
cap = cv2.VideoCapture("stopwatch.avi")
fps = cap.get(cv2.CAP_PROP_FPS)
delay = round(1000 / fps)
while True:
    ret,frame = cap.read()
    if not ret:
        break
    inversed = ~frame
    cv2.imshow('frame', frame)
    cv2.imshow('inversed', inversed)
    if cv2.waitKey(delay) == 27:
        break
cv2.destroyAllWindows()

In [1]:
# 146p drawing.py

In [2]:
import numpy as np

In [3]:
img = np.full((400, 400, 3), 255, np.uint8)

In [5]:
         #     x, y 값                 색           선두께
cv2.line(img, (50, 50), (200, 50), (0, 0, 255))
cv2.line(img, (50, 100), (200, 100), (255, 0, 255), 3)
cv2.line(img, (50, 150), (200, 150), (255, 0, 0), 10)


cv2.line(img, (250, 50), (350, 100), (0, 0, 255), 1, cv2.LINE_4)
cv2.line(img, (250, 70), (350, 120), (255, 0, 255), 1, cv2.LINE_8)
cv2.line(img, (250, 90), (350, 140), (255, 0, 0), 1, cv2.LINE_AA)

cv2.arrowedLine(img, (50, 200), (150, 200), (0, 0, 255), 1)
cv2.arrowedLine(img, (50, 250), (350, 250), (255, 0, 255), 1)
cv2.arrowedLine(img, (50, 300), (350, 300), (255, 0, 0), 1, cv2.LINE_8, 0, 0.05)

cv2.drawMarker(img, (50, 350), (0, 0, 255), cv2.MARKER_CROSS)
cv2.drawMarker(img, (100, 350), (0, 0, 255), cv2.MARKER_TILTED_CROSS)
cv2.drawMarker(img, (150, 350), (0, 0, 255), cv2.MARKER_STAR)
cv2.drawMarker(img, (200, 350), (0, 0, 255), cv2.MARKER_DIAMOND)
cv2.drawMarker(img, (250, 350), (0, 0, 255), cv2.MARKER_SQUARE)
cv2.drawMarker(img, (300, 350), (0, 0, 255), cv2.MARKER_TRIANGLE_UP)
cv2.drawMarker(img, (350, 350), (0, 0, 255), cv2.MARKER_TRIANGLE_DOWN)

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
img = np.full((400, 400, 3), 255, np.uint8)
                                                  #  두께
cv2.rectangle(img, (50, 50), (150, 100), (0, 0, 255), 2)
cv2.rectangle(img, (50, 150), (150, 200), (0, 0, 128), -1)

cv2.circle(img, (300, 120), 30, (255, 255, 0), -1, cv2.LINE_AA)
cv2.circle(img, (300, 120), 60, (255, 0, 0), 3, cv2.LINE_AA)

cv2.ellipse(img, (120, 300), (60, 30), -20, 0, 270, (255, 255, 0), cv2.FILLED, cv2.LINE_AA)
cv2.ellipse(img, (120, 300), (100, 50), 20, 0, 360, (0, 255, 0), 2, cv2.LINE_AA)

pts = np.array([[250, 250], [300, 250], [300, 300], [350, 300], [350, 350], [250, 350]])
cv2.polylines(img, [pts], True, (255, 0, 255), 2)

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img = np.full((500, 800, 3), 255, np.uint8)

cv2.putText(img, "FONT_HERSHEY_SIMPLEX", (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_PLAIN", (20, 100), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_DUPLEX", (20, 150), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 255))
cv2.putText(img, "FONT_HERSHEY_COMPLEX", (20, 200), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_TRIPLEX", (20, 250), cv2.FONT_HERSHEY_TRIPLEX, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_COMPLEX_SMALL", (20, 300), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (255, 0, 0))
cv2.putText(img, "FONT_HERSHEY_SCRIPT_SIMPLEX", (20, 350), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (255, 0, 255))
cv2.putText(img, "FONT_HERSHEY_SCRIPT_COMPLEX", (20, 400), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 1, (255, 0, 255))
cv2.putText(img, "FONT_HERSHEY_COMPLEX | FONT_ITALIC", (20, 450), cv2.FONT_HERSHEY_COMPLEX | cv2.FONT_ITALIC, 1, (255, 0, 0))

cv2.imshow("img", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# 163p mouse.py

In [13]:

def on_mouse(event, x, y, flags, param):
    global oldx, oldy

    if event == cv2.EVENT_LBUTTONDOWN:
        oldx, oldy = x, y
        print('EVENT_LBUTTONDOWN: %d, %d' % (x, y))

    elif event == cv2.EVENT_LBUTTONUP:
        print('EVENT_LBUTTONUP: %d, %d' % (x, y))

    elif event == cv2.EVENT_MOUSEMOVE:
        if flags & cv2.EVENT_FLAG_LBUTTON:
            cv2.line(img, (oldx, oldy), (x, y), (0, 255, 255), 2)
            cv2.imshow('img', img)
            oldx, oldy = x, y


img = cv2.imread('lenna.bmp')

if img is None:
    print('Image load failed!')
    sys.exit()

cv2.namedWindow('img')
cv2.setMouseCallback('img', on_mouse)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


EVENT_LBUTTONDOWN: 347, 138
EVENT_LBUTTONUP: 135, 253


In [1]:
import numpy as np
import cv2

In [2]:
filename = 'mydata.json'

In [3]:
name = 'Jane'
age = 10
pt1 = (100, 200)
scores = (80, 90, 50)
mat1 = np.array([[1.0, 1.5], [2.0, 3.2]], dtype=np.float32)

In [4]:
fs = cv2.FileStorage(filename, cv2.FILE_STORAGE_WRITE)

In [5]:
fs

<FileStorage 0000016332F65350>

In [6]:
fs.write('name', name)
fs.write('age', age)
fs.write('point', pt1)
fs.write('scores', scores)
fs.write('data', mat1)

fs.release()

In [7]:
fs = cv2.FileStorage(filename, cv2.FILE_STORAGE_READ)

In [8]:
fs

<FileStorage 0000016332F65570>

In [9]:
name = fs.getNode('name').string()
name

'Jane'

In [10]:
age = int(fs.getNode('age').real())
age

10

In [11]:
pt1 = tuple(fs.getNode('point').mat().astype(np.int32).flatten())
pt1

(100, 200)

In [12]:
scores = tuple(fs.getNode('scores').mat().flatten())
mat1 = fs.getNode('data').mat()
scores, mat1

((80.0, 90.0, 50.0),
 array([[1. , 1.5],
        [2. , 3.2]], dtype=float32))

In [13]:
fs.release()     # opencv는 뭘 저장할 때 json 형태로 저장

In [14]:
src = cv2.imread('airplane.bmp', cv2.IMREAD_COLOR)
mask = cv2.imread('mask_plane.bmp', cv2.IMREAD_GRAYSCALE)
dst = cv2.imread('field.bmp', cv2.IMREAD_COLOR)

In [15]:
cv2.copyTo(src, mask, dst)

array([[[203, 199, 207],
        [199, 200, 208],
        [202, 201, 211],
        ...,
        [198, 190, 194],
        [195, 188, 190],
        [193, 184, 189]],

       [[203, 199, 207],
        [204, 198, 207],
        [200, 199, 209],
        ...,
        [173, 157, 148],
        [170, 156, 143],
        [184, 173, 166]],

       [[203, 196, 208],
        [204, 196, 208],
        [203, 198, 208],
        ...,
        [152, 129, 109],
        [151, 121, 108],
        [148, 126,  97]],

       ...,

       [[ 51,  29,  15],
        [ 49,  32,  29],
        [ 49,  49,  61],
        ...,
        [ 45,  62,  38],
        [ 46,  75,  56],
        [ 40, 110, 100]],

       [[ 50,  26,  11],
        [ 50,  45,  54],
        [ 47,  44,  50],
        ...,
        [ 49,  56,  35],
        [ 47,  61,  42],
        [ 44,  77,  64]],

       [[ 50,  42,  52],
        [ 46,  71, 108],
        [ 47,  56,  58],
        ...,
        [ 50,  42,  23],
        [ 48,  61,  41],
        [ 47,  62,  46]]

In [16]:
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()

In [17]:
# 205p
src = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)

In [19]:
type(src)

numpy.ndarray

In [18]:
dst = cv2.add(src, 100)

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
# 209p

dst_bright = cv2.add(src, 100)
dst_contrast = cv2.multiply(src, 2.0)

cv2.imshow('src', src)
cv2.imshow('dst_bright', dst_bright)
cv2.imshow('dst_contrast', dst_contrast)
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
# 212p

dst_bright = cv2.add(src, 100)
dst_contrast = cv2.multiply(src, 2.0)
alpha = 1.0
dst_alpha = np.clip(src + (src - 128.)*alpha, 0, 255).astype(np.uint8)


cv2.imshow('src', src)
cv2.imshow('dst_bright', dst_bright)
cv2.imshow('dst_contrast', dst_contrast)
cv2.imshow('dst_alpha', dst_alpha)
cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
def calcGrayHist(img):
    channels = [0]
    histSize = [256]
    histRange = [0, 256]

    hist = cv2.calcHist([img], channels, None, histSize, histRange)

    return hist


def getGrayHistImage(hist):
    histMax = np.max(hist)

    imgHist = np.full((100, 256), 255, dtype=np.uint8)
    for x in range(256):
        pt1 = (x, 100)
        pt2 = (x, 100 - int(hist[x, 0] * 100 / histMax))
        cv2.line(imgHist, pt1, pt2, 0)

    return imgHist

In [25]:
src = cv2.imread('hawkes.bmp', cv2.IMREAD_GRAYSCALE)

In [26]:
cv2.imshow('src', src)
cv2.imshow('srcHist', getGrayHistImage(calcGrayHist(src)))

#cv2.imshow('dst', dst)
#cv2.imshow('dstHist', getGrayHistImage(calcGrayHist(dst)))

cv2.waitKey()
cv2.destroyAllWindows()


In [30]:
# 222p
src = cv2.imread('hawkes.bmp', cv2.IMREAD_GRAYSCALE)


gmin = float(np.min(src))
gmax = float(np.max(src))

dst_st = ((src - gmin) * 255. / (gmax - gmin)).astype(np.uint8)

cv2.imshow('src', src)
cv2.imshow('srcHist', getGrayHistImage(calcGrayHist(src)))

cv2.imshow('dst_st', dst_st)
cv2.imshow('dstHist', getGrayHistImage(calcGrayHist(dst_st)))

cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
# 226

src = cv2.imread('hawkes.bmp', cv2.IMREAD_GRAYSCALE)

dst_eq = cv2.equalizeHist(src)

cv2.imshow('src', src)
cv2.imshow('srcHist', getGrayHistImage(calcGrayHist(src)))

cv2.imshow('dst_eq', dst_eq)
cv2.imshow('dstHist_eq', getGrayHistImage(calcGrayHist(dst_eq)))

cv2.imshow('dst_st', dst_st)
cv2.imshow('dstHist_st', getGrayHistImage(calcGrayHist(dst_st)))

cv2.waitKey()
cv2.destroyAllWindows()


In [37]:
src = cv2.imread('rose.bmp', cv2.IMREAD_GRAYSCALE)

emboss = np.array([[-1, -1, 0],
                   [-1, 0, 1],
                   [0, 1, 1]], np.float32)

dst_d128 = cv2.filter2D(src, -1, emboss, delta=128)
dst_d0 = cv2.filter2D(src, -1, emboss, delta=0)
dst_d255 = cv2.filter2D(src, -1, emboss, delta=255)

cv2.imshow('src', src)
cv2.imshow('dst_d128', dst_d128)
cv2.imshow('dst_d0', dst_d0)
cv2.imshow('dst_d255', dst_d255)
cv2.waitKey()
cv2.destroyAllWindows()

In [38]:
blurring = np.array([[1//9, 1/9, 1/9],
                     [1//9, 1/9, 1/9],
                     [1//9, 1/9, 1/9]], np.float32)

In [39]:
dst_blur = cv2.filter2D(src, -1, blurring, delta =0)

In [41]:
cv2.imshow('src', src)
cv2.imshow('dst_blur', dst_blur)
cv2.waitKey()
cv2.destroyAllWindows()

In [42]:
# 267p

src = cv2.imread('lenna.bmp', cv2.IMREAD_GRAYSCALE)

cv2.imshow('src', src)

for stddev in [10, 20, 30]:
    noise = np.zeros(src.shape, np.int32)
    cv2.randn(noise, 0, stddev)

    dst = cv2.add(src, noise, dtype=cv2.CV_8UC1)

    desc = 'stddev = %d' % stddev
    cv2.putText(dst, desc, (10, 30), cv2.FONT_HERSHEY_SIMPLEX,
               1.0, 255, 1, cv2.LINE_AA)
    cv2.imshow('dst', dst)
    cv2.waitKey()

cv2.destroyAllWindows()

In [44]:
# 280p

src = cv2.imread('tekapo.bmp')

In [45]:
rows = src.shape[0]
cols = src.shape[1]

In [46]:
src_pts = np.array([[0, 0],
                    [cols - 1, 0],
                    [cols - 1, rows - 1]]).astype(np.float32)
dst_pts = np.array([[50, 50],
                    [cols - 100, 100],
                    [cols - 50, rows - 50]]).astype(np.float32)

affine_mat = cv2.getAffineTransform(src_pts, dst_pts)

dst = cv2.warpAffine(src, affine_mat, (0, 0))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [47]:
src = cv2.imread('tekapo.bmp')

affine_mat = np.array([[1, 0, 150],
                       [0, 1, 100]]).astype(np.float32)

dst = cv2.warpAffine(src, affine_mat, (0, 0))

cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [48]:

# 300p

def on_mouse(event, x, y, flags, param):
    global cnt, src_pts
    if event == cv2.EVENT_LBUTTONDOWN:
        if cnt < 4:
            src_pts[cnt, :] = np.array([x, y]).astype(np.float32)
            cnt += 1

            cv2.circle(src, (x, y), 5, (0, 0, 255), -1)
            cv2.imshow('src', src)
        
        if cnt == 4:
            w = 200
            h = 300

            dst_pts = np.array([[0, 0],
                                [w - 1, 0],
                                [w - 1, h - 1],
                                [0, h - 1]]).astype(np.float32)

            pers_mat = cv2.getPerspectiveTransform(src_pts, dst_pts)

            dst = cv2.warpPerspective(src, pers_mat, (w, h))

            cv2.imshow('dst', dst)

In [51]:
cnt = 0
src_pts = np.zeros([4, 2], dtype=np.float32)
src = cv2.imread('card.bmp')

if src is None:
    print('Image load failed!')
    sys.exit()

cv2.namedWindow('src')
cv2.setMouseCallback('src', on_mouse)

cv2.imshow('src', src)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [56]:
src = cv2.imread('kids.png')

classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


faces = classifier.detectMultiScale(src)

for (x, y, w, h) in faces:
    cv2.rectangle(src, (x, y), (x + w, y + h), (255, 0, 255), 2)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

In [58]:
src = cv2.imread('kids.png')

face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('haarcascade_eye.xml')

faces = face_classifier.detectMultiScale(src)

for (x1, y1, w1, h1) in faces:
    cv2.rectangle(src, (x1, y1), (x1 + w1, y1 + h1), (255, 0, 255), 2)

    faceROI = src[y1:y1 + h1, x1:x1 + w1]
    eyes = eye_classifier.detectMultiScale(faceROI)

    for (x2, y2, w2, h2) in eyes:
        center = (int(x2 + w2 / 2), int(y2 + h2 / 2))
        cv2.circle(faceROI, center, int(w2 / 2), (255, 0, 0), 2, cv2.LINE_AA)

cv2.imshow('src', src)
cv2.waitKey()
cv2.destroyAllWindows()

